# GCC production
gcc-release:
  tags:
    - disco
  script:
    - export PATH=/usr/lib/ccache:$PATH
    - export CXX=g++-9
    - export CC=gcc-9
    - export BOOST_ROOT=~/boost_1_71_0
    - mkdir -p build-release
    - cd build-release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - ninja -j8 http-client net-web_server-sample net-wss_client-sample

# Clang debug with address sanitizer
clang-debug-asan:
  tags:
    - disco
  script:
    - export ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer
    - export PATH=/usr/lib/ccache:$PATH
    - export UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1
    - export CXXFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -stdlib=libc++"
    - export BOOST_ROOT=~/boost_1_71_0-libc++
    - export CXX=clang++-9
    - export CC=clang-9
    - mkdir -p build-clang-debug-asan
    - cd build-clang-debug-asan
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCTX_ASAN=true ..
    - ninja -j8 http-client net-web_server-sample net-wss_client-sample

# GCC debug valgrind
gcc-debug-valgrind:
  tags:
    - disco
  script:
    - export PATH=/usr/lib/ccache:$PATH
    - export CXX=g++-9
    - export CC=gcc-9
    - export BOOST_ROOT=~/boost_1_71_0
    #- export CXXFLAGS="-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC" TODO(felix) currently not working with OSRM
    - git submodule update --init --recursive
    - mkdir -p build-gcc-debug-valgrind
    - cd build-gcc-debug-valgrind
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCTX_VALGRIND=true ..
    - ninja -j8 http-client net-web_server-sample net-wss_client-sample

# MSVC release
msvc-release:
  tags:
    - windows
  script:
    - set WD=%cd%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - cd %WD%
    - set BOOST_ROOT=C:\boost_1_70_0
    - git submodule update --init --recursive
    - mkdir build-msvc-release
    - cd build-msvc-release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DZLIB_ROOT=C:\zlib-1.2.8 ..
    - ninja -j8 http-client net-web_server-sample net-wss_client-sample

# MSVC debug
msvc-debug:
  tags:
    - windows
  script:
    - set WD=%cd%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - cd %WD%
    - set BOOST_ROOT=C:\boost_1_70_0
    - git submodule update --init --recursive
    - mkdir build-msvc-debug
    - cd build-msvc-debug
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DZLIB_ROOT=C:\zlib-1.2.8 ..
    - ninja -j8 http-client net-web_server-sample net-wss_client-sample

# Clang-Tidy
clang-tidy:
  tags:
    - disco
  script:
    - export PATH=/usr/lib/ccache:$PATH
    - export CXXFLAGS=-stdlib=libc++
    - export BOOST_ROOT=~/boost_1_71_0-libc++
    - export CXX=clang++-9
    - export CC=clang-9
    - mkdir build-clang-tidy
    - cd build-clang-tidy
    - cmake -GNinja -DNET_LINT=ON ..
    - ninja

# Clang-Format
clang-format:
  tags:
    - disco
  script:
    - export BOOST_ROOT=~/boost_1_71_0-libc++
    - mkdir build-clang-format
    - cd build-clang-format
    - cmake -GNinja ..
    - ninja net-format-check
